name: CraveHaven CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  node-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Validate Backend Syntax
        working-directory: server
        run: npm run check

      - name: Install Client Dependencies
        working-directory: client
        run: npm install

      - name: Build Frontend
        working-directory: client
        run: npm run build


  docker-build:
    runs-on: ubuntu-latest
    needs: node-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build -t amithsubodh/cravehaven-backend:latest ./server
          docker push amithsubodh/cravehaven-backend:latest

      - name: Build Frontend Image
        run: |
          docker build -t amithsubodh/cravehaven-frontend:latest ./client
          docker push amithsubodh/cravehaven-frontend:latest

      - name: Validate docker-compose File
        run: docker compose -f docker-compose.yml config
